# Generated by Django 5.2.1 on 2025-05-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_vote_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(default='Poll Description'),
        ),
        migrations.AddField(
            model_name='poll',
            name='title',
            field=models.CharField(default='Poll Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='poll',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
